### ISSUE TITLE
My contract isn't working properly as intended so i want to migrate

### ISSUE THREAD

**Issue by zakimzf** [FreezyEx/Migrate-Contract#1]
Sell fee isn't working proerly for my contract since i cannot modify the contract i am looking to create another contract which will rectify the errors in the 1st one..

Does it mean i can use the contract int his repository to migrate my contract? 
Also the LP is locked for the contract how would it work after migration?
Please answer!

**Comment by FreezyEx** [comment]
This contract can be used to migrate to a new token's version. Of course it must be adjusted absed on your case. I highly recommend to check the code and try to understand if it is what you need
